modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
credits="Thanks to Harry Talks for his amazing tutorials." #optional
authors="Harry" #optional

[[mods]] #mandatory
modId="tutorialmod" #mandatory
version="0.1.0" #mandatory
displayName="Harry's Tutorial Mod" #mandatory
description='''
This is my mod.
It's great.
Thank You PewDiePie
'''

[[dependencies.tutorialmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.tutorialmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"